Train:
  batch_size: 32
  learning_rate: 0.55
  reg: 0.0005
  epochs: 10
  momentum: 0.9
  debug: True

Model:
  type: TwoLayerNet # SoftmaxRegression or TwoLayerNet
  hidden_size: 256 # only applicable for TwolayerNet