data:
  dataset: fashionmnist # mnist   
train:
  batch_size: 64 #64
  lr: 0.0002  # 0.0001
  n_epochs: 50   # 5
  num_workers: 4 # change this based on number of cores on your CPU. 4 is sufficient for 1 gpu. If unsure leave at 1.  
network:
  model: gan # vae, gan, diffusion
  hidden_dim: 800 # used for VAE and gan
  latent_dim: 20 # used for VAE or gan
vae:
  vae_recon_loss: l2  # l1 or l2
  beta: 2 #2
diffusion:
  time_dim: 128
  timesteps: 500
optimizer:
  type: 'adamw' # adamw or sgd
  weight_decay: 0.002 #0.001
gan:
  leaky: False  # false
